"""Shared application and schema versions."""

APP_VERSION = "3.0.0-dev"
API_VERSION = "v1"
AUDIT_SCHEMA_VERSION = "3.0"
KNOWLEDGE_PACK_SCHEMA_VERSION = "1.0"
REPORT_SCHEMA_VERSION = "3.0"
PARSER_VERSION = "3.0.0"
COMPARISON_ENGINE_VERSION = "3.0.0"
