/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_api_v1_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Settings */
        get: operations["public_settings_api_v1_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/audit-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit History */
        get: operations["audit_history_api_v1_settings_audit_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/local-audit-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Local Audit Data */
        delete: operations["delete_local_audit_data_api_v1_settings_local_audit_data_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/clear-temporary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Temporary Files */
        post: operations["clear_temporary_files_api_v1_settings_clear_temporary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/clear-token-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Token Cache */
        post: operations["clear_token_cache_api_v1_settings_clear_token_cache_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Application Settings */
        post: operations["reset_application_settings_api_v1_settings_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostics */
        get: operations["diagnostics_api_v1_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deviations/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Deviations */
        post: operations["validate_deviations_api_v1_deviations_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Demo Audit */
        post: operations["create_demo_audit_api_v1_audits_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Offline Audit */
        post: operations["preview_offline_audit_api_v1_audits_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Offline Audit */
        post: operations["create_offline_audit_api_v1_audits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits/{audit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit */
        get: operations["get_audit_api_v1_audits__audit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits/{audit_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_audits__audit_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits/{audit_id}/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policies */
        get: operations["policies_api_v1_audits__audit_id__policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits/{audit_id}/policies/{policy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Policy Detail */
        get: operations["policy_detail_api_v1_audits__audit_id__policies__policy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits/{audit_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Findings */
        get: operations["findings_api_v1_audits__audit_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits/{audit_id}/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finding Detail */
        get: operations["finding_detail_api_v1_audits__audit_id__findings__finding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits/{audit_id}/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conflicts */
        get: operations["conflicts_api_v1_audits__audit_id__conflicts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits/{audit_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Catalog */
        get: operations["report_catalog_api_v1_audits__audit_id__reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audits/{audit_id}/reports/{report_format}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Report */
        get: operations["download_report_api_v1_audits__audit_id__reports__report_format__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Packs */
        get: operations["list_knowledge_packs_api_v1_knowledge_packs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-packs/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Knowledge Pack */
        post: operations["validate_knowledge_pack_api_v1_knowledge_packs_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-packs/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Knowledge Pack */
        post: operations["import_knowledge_pack_api_v1_knowledge_packs_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-packs/{pack_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Pack */
        post: operations["activate_pack_api_v1_knowledge_packs__pack_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-packs/{pack_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Pack */
        post: operations["deactivate_pack_api_v1_knowledge_packs__pack_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-packs/{pack_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Pack */
        delete: operations["remove_pack_api_v1_knowledge_packs__pack_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-packs/{pack_id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pack Provenance */
        get: operations["pack_provenance_api_v1_knowledge_packs__pack_id__provenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-packs/{pack_id}/validation-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Pack Validation Report */
        get: operations["export_pack_validation_report_api_v1_knowledge_packs__pack_id__validation_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_tenant_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/device-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin Device Code */
        post: operations["begin_device_code_api_v1_tenant_device_code_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin Device Code */
        post: operations["begin_device_code_api_v1_tenant_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/device-code/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Device Code */
        post: operations["complete_device_code_api_v1_tenant_device_code_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/retrieve/{operation}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve */
        get: operations["retrieve_api_v1_tenant_retrieve__operation__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenant/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Out */
        post: operations["sign_out_api_v1_tenant_signout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptedDeviation */
        AcceptedDeviation: {
            /** Deviation Id */
            deviation_id: string;
            /** Schema Version */
            schema_version: string;
            /** Canonical Setting Id */
            canonical_setting_id: string;
            /** Policy Id */
            policy_id?: string | null;
            accepted_value: components["schemas"]["JsonValue"];
            /** Reason */
            reason: string;
            /** Owner */
            owner: string;
            /** Approver */
            approver: string;
            /** Ticket */
            ticket: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /**
             * Valid Until
             * Format: date
             */
            valid_until: string;
        };
        /**
         * AlignmentStatus
         * @enum {string}
         */
        AlignmentStatus: "aligned" | "more_restrictive" | "less_restrictive" | "different" | "accepted_deviation" | "expired_deviation" | "not_in_selected_baseline" | "not_applicable" | "unsupported" | "not_evaluable";
        /**
         * ApplicabilityState
         * @enum {string}
         */
        ApplicabilityState: "applicable" | "not_applicable" | "unknown";
        /** AssignmentFilter */
        AssignmentFilter: {
            /** Filter Id */
            filter_id?: string | null;
            /** Display Name */
            display_name?: string | null;
            mode: components["schemas"]["FilterMode"];
            /** Rule */
            rule?: string | null;
            /** @default unknown */
            platform: components["schemas"]["Platform"];
            /**
             * Definition Available
             * @default false
             */
            definition_available: boolean;
        };
        /** AssignmentRisk */
        AssignmentRisk: {
            /** Risk Id */
            risk_id: string;
            /** Policy Id */
            policy_id: string;
            /** Risk Type */
            risk_type: string;
            severity: components["schemas"]["FindingSeverity"];
            /** Explanation */
            explanation: {
                [key: string]: string;
            };
            /** Recommended Action */
            recommended_action: {
                [key: string]: string;
            };
        };
        /** AssignmentTarget */
        AssignmentTarget: {
            target_type: components["schemas"]["AssignmentTargetType"];
            /** Target Id */
            target_id?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** @default unknown */
            scope: components["schemas"]["Scope"];
            filter?: components["schemas"]["AssignmentFilter"] | null;
        };
        /**
         * AssignmentTargetType
         * @enum {string}
         */
        AssignmentTargetType: "all_users" | "all_devices" | "group" | "exclusion_group" | "unknown";
        /** AuditConfiguration */
        AuditConfiguration: {
            /**
             * Language
             * @default de
             */
            language: string;
            /** Active Pack Ids */
            active_pack_ids: string[];
            /**
             * Exact Only
             * @default true
             */
            exact_only: boolean;
            /**
             * History Enabled
             * @default false
             */
            history_enabled: boolean;
            /**
             * Save Reports
             * @default false
             */
            save_reports: boolean;
            context?: components["schemas"]["AuditContext"];
            /** Organization Requirements */
            organization_requirements?: components["schemas"]["OrganizationRequirement"][];
        };
        /** AuditContext */
        AuditContext: {
            /** Os Version */
            os_version?: string | null;
            /** Edition */
            edition?: string | null;
            /** Architecture */
            architecture?: string | null;
            /** Enrollment Type */
            enrollment_type?: string | null;
            /** Supervised */
            supervised?: boolean | null;
            /** Granted Licenses */
            granted_licenses?: string[];
            /** Physical Device */
            physical_device?: boolean | null;
            /** Vdi */
            vdi?: boolean | null;
            /** Shared Device */
            shared_device?: boolean | null;
            /** Pilot Context */
            pilot_context?: string | null;
            /** Environment Notes */
            environment_notes?: string | null;
        };
        /**
         * AuditMode
         * @enum {string}
         */
        AuditMode: "offline" | "tenant" | "demo";
        /** AuditPreview */
        AuditPreview: {
            /** Policy Count */
            policy_count: number;
            /** Setting Count */
            setting_count: number;
            /** Policies */
            policies: components["schemas"]["AuditPreviewPolicy"][];
            /** Diagnostics */
            diagnostics: components["schemas"]["ParserDiagnostic"][];
            /** Input Sha256 */
            input_sha256: string;
            /** Parser Version */
            parser_version: string;
        };
        /** AuditPreviewPolicy */
        AuditPreviewPolicy: {
            /** Policy Id */
            policy_id: string;
            /** Name */
            name: string;
            platform: components["schemas"]["Platform"];
            kind: components["schemas"]["PolicyKind"];
            /** Setting Count */
            setting_count: number;
        };
        /** AuditResult */
        AuditResult: {
            /** Audit Id */
            audit_id: string;
            /**
             * Schema Version
             * @default 3.0
             */
            schema_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            mode: components["schemas"]["AuditMode"];
            /** Is Synthetic */
            is_synthetic: boolean;
            configuration: components["schemas"]["AuditConfiguration"];
            /** Policies */
            policies: components["schemas"]["PolicyEvaluation"][];
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Conflicts */
            conflicts: components["schemas"]["ConflictResult"][];
            /** Assignment Risks */
            assignment_risks: components["schemas"]["AssignmentRisk"][];
            /** Diagnostics */
            diagnostics: components["schemas"]["ParserDiagnostic"][];
            coverage: components["schemas"]["CoverageMetrics"];
            decision: components["schemas"]["DecisionResult"];
            /** Selected Pack Manifests */
            selected_pack_manifests: components["schemas"]["KnowledgePackManifest"][];
        };
        /** AuthenticationResult */
        AuthenticationResult: {
            /** Authenticated */
            authenticated: boolean;
            /** Granted Scopes */
            granted_scopes: string[];
            /** Account Name */
            account_name?: string | null;
        };
        /** Body_create_offline_audit_api_v1_audits_post */
        Body_create_offline_audit_api_v1_audits_post: {
            /**
             * Files
             * @description Intune JSON exports or safe ZIP archives
             */
            files: string[];
            /**
             * Knowledge Pack Ids
             * @default ["synthetic.test-baseline"]
             */
            knowledge_pack_ids: string;
            /**
             * Language
             * @default de
             */
            language: string;
            /** Deviations */
            deviations?: string | null;
            /** Organization Requirements */
            organization_requirements?: string | null;
            /**
             * Audit Context
             * @default {}
             */
            audit_context: string;
        };
        /** Body_import_knowledge_pack_api_v1_knowledge_packs_import_post */
        Body_import_knowledge_pack_api_v1_knowledge_packs_import_post: {
            /**
             * Pack
             * @description Validated knowledge-pack ZIP
             */
            pack: string;
        };
        /** Body_preview_offline_audit_api_v1_audits_preview_post */
        Body_preview_offline_audit_api_v1_audits_preview_post: {
            /**
             * Files
             * @description Intune JSON exports or safe ZIP archives
             */
            files: string[];
        };
        /** Body_validate_deviations_api_v1_deviations_validate_post */
        Body_validate_deviations_api_v1_deviations_validate_post: {
            /**
             * Deviations
             * @description Accepted-deviation JSON file
             */
            deviations: string;
        };
        /** Body_validate_knowledge_pack_api_v1_knowledge_packs_validate_post */
        Body_validate_knowledge_pack_api_v1_knowledge_packs_validate_post: {
            /**
             * Pack
             * @description ZIP containing one manifest.json and settings JSON
             */
            pack: string;
        };
        /** CompleteDeviceCode */
        CompleteDeviceCode: {
            /** Flow Id */
            flow_id: string;
        };
        /**
         * ConflictConfidence
         * @enum {string}
         */
        ConflictConfidence: "confirmed" | "probable" | "possible" | "none";
        /** ConflictResult */
        ConflictResult: {
            /** Conflict Id */
            conflict_id: string;
            confidence: components["schemas"]["ConflictConfidence"];
            /** Classification */
            classification: string;
            /** Canonical Setting Id */
            canonical_setting_id: string;
            /** Policy A Id */
            policy_a_id: string;
            /** Policy A Name */
            policy_a_name: string;
            policy_a_value: components["schemas"]["JsonValue"];
            /** Policy B Id */
            policy_b_id: string;
            /** Policy B Name */
            policy_b_name: string;
            policy_b_value: components["schemas"]["JsonValue"];
            /** Assignments A */
            assignments_a: components["schemas"]["AssignmentTarget"][];
            /** Assignments B */
            assignments_b: components["schemas"]["AssignmentTarget"][];
            /** Overlap Result */
            overlap_result: string;
            /** Reasoning */
            reasoning: {
                [key: string]: string;
            };
            /** Affected Device Count */
            affected_device_count?: number | null;
            /** Recommended Action */
            recommended_action: {
                [key: string]: string;
            };
        };
        /** CoverageMetrics */
        CoverageMetrics: {
            /** Parser Coverage */
            parser_coverage?: number | null;
            /** Technical Extraction Confidence */
            technical_extraction_confidence?: number | null;
            /** Exact Setting Coverage */
            exact_setting_coverage?: number | null;
            /** Exact Value Semantic Coverage */
            exact_value_semantic_coverage?: number | null;
            /** Microsoft Baseline Coverage */
            microsoft_baseline_coverage?: number | null;
            /** Documentation Coverage */
            documentation_coverage?: number | null;
            /** Assignment Analysis Coverage */
            assignment_analysis_coverage?: number | null;
            /** Conflict Analysis Coverage */
            conflict_analysis_coverage?: number | null;
            /** Runtime Evidence Coverage */
            runtime_evidence_coverage?: number | null;
            /** Evaluable Settings */
            evaluable_settings: number;
            /** Not Evaluable Settings */
            not_evaluable_settings: number;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Decision */
            decision: string;
            /** Reason */
            reason: {
                [key: string]: string;
            };
            /** Next Action */
            next_action: {
                [key: string]: string;
            };
            /** Is Synthetic */
            is_synthetic: boolean;
            /** Policy Count */
            policy_count: number;
            /** Setting Count */
            setting_count: number;
            /** Evaluable Count */
            evaluable_count: number;
            /** Not Evaluable Count */
            not_evaluable_count: number;
            /** Confirmed Issues */
            confirmed_issues: number;
            /** Confirmed Conflicts */
            confirmed_conflicts: number;
            /** Alignment Counts */
            alignment_counts: {
                [key: string]: number;
            };
            /** Severity Counts */
            severity_counts: {
                [key: string]: number;
            };
            /** Exact Evidence Coverage */
            exact_evidence_coverage: number | null;
            /** Assignment Analysis Coverage */
            assignment_analysis_coverage: number | null;
            /** Runtime Success Rate */
            runtime_success_rate?: number | null;
            /** Runtime Success Count */
            runtime_success_count?: number | null;
            /** Runtime Targeted Count */
            runtime_targeted_count?: number | null;
            evidence_quality: components["schemas"]["EvidenceConfidence"];
            /** Policy Health Counts */
            policy_health_counts: {
                [key: string]: number;
            };
            /** Not Evaluable Reasons */
            not_evaluable_reasons: {
                [key: string]: number;
            };
            /** Top Actions */
            top_actions: components["schemas"]["Finding"][];
        };
        /** DecisionResult */
        DecisionResult: {
            status: components["schemas"]["DecisionStatus"];
            /** Title */
            title: {
                [key: string]: string;
            };
            /** Reason */
            reason: {
                [key: string]: string;
            };
            /** Blocking Conditions */
            blocking_conditions: string[];
            /** Nonblocking Warnings */
            nonblocking_warnings: string[];
            /** Next Action */
            next_action: {
                [key: string]: string;
            };
            /** Evidence Summary */
            evidence_summary: {
                [key: string]: string;
            };
            /** Failed Gates */
            failed_gates: string[];
            /** Decision Trace */
            decision_trace: components["schemas"]["DecisionTraceStep"][];
        };
        /**
         * DecisionStatus
         * @enum {string}
         */
        DecisionStatus: "aligned_with_selected_baseline" | "aligned_with_accepted_deviations" | "changes_required_before_pilot" | "pilot_recommended" | "manual_review_required" | "insufficient_evidence" | "runtime_remediation_required";
        /** DecisionTraceStep */
        DecisionTraceStep: {
            /** Order */
            order: number;
            /** Gate */
            gate: string;
            /** Outcome */
            outcome: string;
            /** Explanation */
            explanation: {
                [key: string]: string;
            };
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** DeviationValidationResult */
        DeviationValidationResult: {
            /** Valid */
            valid: boolean;
            /** Deviation Count */
            deviation_count: number;
            /** Deviation Ids */
            deviation_ids: string[];
        };
        /** DeviceCodePrompt */
        DeviceCodePrompt: {
            /** Flow Id */
            flow_id: string;
            /** User Code */
            user_code: string;
            /** Verification Uri */
            verification_uri: string;
            /** Message */
            message: string;
            /** Expires In */
            expires_in: number;
            /** Interval */
            interval: number;
        };
        /**
         * DiagnosticSeverity
         * @enum {string}
         */
        DiagnosticSeverity: "error" | "warning" | "information";
        /** DiagnosticsResult */
        DiagnosticsResult: {
            /** Application Version */
            application_version: string;
            /** Api Version */
            api_version: string;
            /** Offline Mode Ready */
            offline_mode_ready: boolean;
            /** Knowledge Pack Count */
            knowledge_pack_count: number;
            /** Active Knowledge Pack Count */
            active_knowledge_pack_count: number;
            /** Tenant Configured */
            tenant_configured: boolean;
            /** Tenant Authenticated */
            tenant_authenticated: boolean;
            /** Notes */
            notes: string[];
        };
        /**
         * EvidenceConfidence
         * @enum {string}
         */
        EvidenceConfidence: "exact" | "strong" | "partial" | "inferred" | "unknown";
        /** EvidenceSource */
        EvidenceSource: {
            evidence_type: components["schemas"]["EvidenceType"];
            /** Title */
            title: string;
            /** Source Reference */
            source_reference: string;
            /** Source Domain */
            source_domain: string;
            /** Published At */
            published_at?: string | null;
            /**
             * Verified At
             * Format: date
             */
            verified_at: string;
            /** Sha256 */
            sha256?: string | null;
            confidence: components["schemas"]["EvidenceConfidence"];
            /** Is Official */
            is_official: boolean;
        };
        /**
         * EvidenceType
         * @enum {string}
         */
        EvidenceType: "microsoft_security_baseline" | "microsoft_csp_documentation" | "microsoft_intune_documentation" | "microsoft_graph_metadata" | "microsoft_runtime_report" | "microsoft_security_compliance_toolkit" | "apple_platform_documentation" | "organizational_requirement" | "accepted_deviation" | "category_only" | "unknown";
        /**
         * FilterMode
         * @enum {string}
         */
        FilterMode: "include" | "exclude";
        /** Finding */
        Finding: {
            /** Finding Id */
            finding_id: string;
            severity: components["schemas"]["FindingSeverity"];
            finding_type: components["schemas"]["FindingType"];
            /** Policy Id */
            policy_id: string;
            /** Policy Name */
            policy_name: string;
            /** Setting Id */
            setting_id: string;
            /** Setting Name */
            setting_name: {
                [key: string]: string;
            };
            configured_value: components["schemas"]["JsonValue"];
            microsoft_value?: components["schemas"]["JsonValue"];
            alignment: components["schemas"]["AlignmentStatus"];
            raw_alignment?: components["schemas"]["AlignmentStatus"] | null;
            /** Title */
            title: {
                [key: string]: string;
            };
            /** Explanation */
            explanation: {
                [key: string]: string;
            };
            /** Why It Matters */
            why_it_matters: {
                [key: string]: string;
            };
            /** User Impact */
            user_impact: {
                [key: string]: string;
            };
            /** Business Impact */
            business_impact: {
                [key: string]: string;
            };
            /** Recommended Action */
            recommended_action: {
                [key: string]: string;
            };
            /** Pilot Suggestion */
            pilot_suggestion: {
                [key: string]: string;
            };
            /** Rollback Suggestion */
            rollback_suggestion: {
                [key: string]: string;
            };
            evidence_confidence: components["schemas"]["EvidenceConfidence"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceSource"][];
            /** Baseline Product */
            baseline_product?: string | null;
            /** Baseline Version */
            baseline_version?: string | null;
            /** Verification Date */
            verification_date?: string | null;
            /** Decision Trace */
            decision_trace: components["schemas"]["DecisionTraceStep"][];
            /** Assignments */
            assignments: components["schemas"]["AssignmentTarget"][];
            /** Affected Device Count */
            affected_device_count?: number | null;
            /** Deviation State */
            deviation_state?: string | null;
            accepted_deviation?: components["schemas"]["AcceptedDeviation"] | null;
            applicability: components["schemas"]["ApplicabilityState"];
            runtime_evidence?: components["schemas"]["RuntimeEvidence"] | null;
            /** Not Evaluable Reasons */
            not_evaluable_reasons?: string[];
        };
        /**
         * FindingSeverity
         * @enum {string}
         */
        FindingSeverity: "critical" | "high" | "medium" | "low" | "information" | "none";
        /**
         * FindingType
         * @enum {string}
         */
        FindingType: "baseline_deviation" | "confirmed_conflict" | "probable_conflict" | "possible_conflict" | "assignment_risk" | "broad_assignment" | "missing_assignment" | "unsupported_setting" | "deprecated_setting" | "runtime_error" | "runtime_conflict" | "expired_deviation" | "insufficient_evidence";
        /** GraphCollectionResult */
        GraphCollectionResult: {
            /** Operation */
            operation: string;
            /** Api Version */
            api_version: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Items */
            items: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Failures */
            failures?: components["schemas"]["GraphFailure"][];
            /**
             * Partial
             * @default false
             */
            partial: boolean;
            /** Correlation Ids */
            correlation_ids: string[];
            /**
             * From Cache
             * @default false
             */
            from_cache: boolean;
        };
        /** GraphFailure */
        GraphFailure: {
            /** Operation */
            operation: string;
            /** Page */
            page: number;
            /** Status Code */
            status_code?: number | null;
            /** Reason */
            reason: string;
            /** Correlation Id */
            correlation_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Offline Mode Available */
            offline_mode_available: boolean;
        };
        JsonValue: unknown;
        /** KnowledgePackManifest */
        KnowledgePackManifest: {
            /** Schema Version */
            schema_version: string;
            /** Pack Id */
            pack_id: string;
            /** Vendor */
            vendor: string;
            /** Product */
            product: string;
            /** Baseline Name */
            baseline_name: string;
            /** Baseline Version */
            baseline_version: string;
            platform: components["schemas"]["Platform"];
            source_type: components["schemas"]["EvidenceType"];
            /** Source Title */
            source_title: string;
            /** Source Domain */
            source_domain: string;
            /** Source Reference */
            source_reference: string;
            /** Published At */
            published_at?: string | null;
            /**
             * Verified At
             * Format: date
             */
            verified_at: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /** Data Sha256 */
            data_sha256: string;
            /** Schema Sha256 */
            schema_sha256: string;
            /** Application Version */
            application_version: string;
            status: components["schemas"]["KnowledgePackStatus"];
            /** Setting Count */
            setting_count: number;
            /** Exact Value Count */
            exact_value_count: number;
            /** Notes */
            notes?: string[];
            /** Settings File */
            settings_file: string;
            provenance?: components["schemas"]["KnowledgeProvenance"];
        };
        /**
         * KnowledgePackStatus
         * @enum {string}
         */
        KnowledgePackStatus: "synthetic" | "verified" | "pending_review" | "invalid";
        /** KnowledgePackSummary */
        KnowledgePackSummary: {
            /** Pack Id */
            pack_id: string;
            /** Name */
            name: string;
            /** Vendor */
            vendor: string;
            /** Product */
            product: string;
            /** Version */
            version: string;
            /** Platform */
            platform: string;
            /** Status */
            status: string;
            /**
             * Verification Date
             * Format: date
             */
            verification_date: string;
            /** Source */
            source: string;
            /** Data Sha256 */
            data_sha256: string;
            /** Setting Count */
            setting_count: number;
            /** Exact Value Count */
            exact_value_count: number;
            /** Age Days */
            age_days: number;
            /** Stale */
            stale: boolean;
            /** Validation State */
            validation_state: string;
            /** Active */
            active: boolean;
            /** Synthetic */
            synthetic: boolean;
        };
        /** KnowledgeProvenance */
        KnowledgeProvenance: {
            /** Input Files */
            input_files?: string[];
            /** Input Sha256 */
            input_sha256?: string[];
            /** Importer Version */
            importer_version?: string | null;
            /** Notes */
            notes?: string[];
        };
        /** LocalPreferences */
        LocalPreferences: {
            /**
             * History Enabled
             * @default false
             */
            history_enabled: boolean;
            /**
             * Retention Days
             * @default 30
             */
            retention_days: number;
            /**
             * Save Reports
             * @default false
             */
            save_reports: boolean;
            /**
             * Automatic Cleanup
             * @default true
             */
            automatic_cleanup: boolean;
        };
        /** OrganizationRequirement */
        OrganizationRequirement: {
            /** Requirement Id */
            requirement_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Applies To */
            applies_to?: string[];
        };
        /** PackValidationIssue */
        PackValidationIssue: {
            /** Code */
            code: string;
            /** Path */
            path: string;
            /** Message */
            message: string;
        };
        /** PackValidationReport */
        PackValidationReport: {
            /** Valid */
            valid: boolean;
            /** Pack Id */
            pack_id?: string | null;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at?: string;
            /** Calculated Data Sha256 */
            calculated_data_sha256?: string | null;
            /** Issues */
            issues?: components["schemas"]["PackValidationIssue"][];
        };
        /** PaginatedResponse[ConflictResult] */
        PaginatedResponse_ConflictResult_: {
            /** Items */
            items: components["schemas"]["ConflictResult"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PaginatedResponse[Finding] */
        PaginatedResponse_Finding_: {
            /** Items */
            items: components["schemas"]["Finding"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PaginatedResponse[PolicyEvaluation] */
        PaginatedResponse_PolicyEvaluation_: {
            /** Items */
            items: components["schemas"]["PolicyEvaluation"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** ParserDiagnostic */
        ParserDiagnostic: {
            /** Source File */
            source_file: string;
            /** Policy */
            policy?: string | null;
            /** Json Path */
            json_path: string;
            /** Code */
            code: string;
            severity: components["schemas"]["DiagnosticSeverity"];
            /** Reason */
            reason: string;
            /** Suggested Action */
            suggested_action: string;
        };
        /**
         * Platform
         * @enum {string}
         */
        Platform: "windows" | "macos" | "ios" | "ipados" | "android" | "linux" | "unknown";
        /** PolicyDocument */
        PolicyDocument: {
            /** Policy Id */
            policy_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            platform: components["schemas"]["Platform"];
            kind: components["schemas"]["PolicyKind"];
            scope: components["schemas"]["Scope"];
            source: components["schemas"]["UploadedSource"];
            /** Settings */
            settings?: components["schemas"]["SettingObservation"][];
            /** Assignments */
            assignments?: components["schemas"]["AssignmentTarget"][];
            /** Diagnostics */
            diagnostics?: components["schemas"]["ParserDiagnostic"][];
            /**
             * Is Synthetic
             * @default false
             */
            is_synthetic: boolean;
        };
        /** PolicyEvaluation */
        PolicyEvaluation: {
            policy: components["schemas"]["PolicyDocument"];
            /** Settings */
            settings: components["schemas"]["SettingEvaluation"][];
            /** Findings */
            findings: components["schemas"]["Finding"][];
            /** Assignment Risks */
            assignment_risks?: components["schemas"]["AssignmentRisk"][];
            runtime_evidence?: components["schemas"]["RuntimeEvidence"] | null;
        };
        /**
         * PolicyKind
         * @enum {string}
         */
        PolicyKind: "settings_catalog" | "endpoint_security" | "security_baseline" | "device_configuration" | "compliance" | "administrative_templates" | "custom" | "unknown";
        /** PublicSettings */
        PublicSettings: {
            /**
             * History Enabled
             * @default false
             */
            history_enabled: boolean;
            /**
             * Retention Days
             * @default 30
             */
            retention_days: number;
            /**
             * Save Reports
             * @default false
             */
            save_reports: boolean;
            /**
             * Automatic Cleanup
             * @default true
             */
            automatic_cleanup: boolean;
            /** Bind Address */
            bind_address: string;
            /** Tenant Mode Configured */
            tenant_mode_configured: boolean;
            /**
             * Raw Uploads Retained
             * @default false
             */
            raw_uploads_retained: boolean;
        };
        /** ResponseEnvelope[AuditPreview] */
        ResponseEnvelope_AuditPreview_: {
            data: components["schemas"]["AuditPreview"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[AuditResult] */
        ResponseEnvelope_AuditResult_: {
            data: components["schemas"]["AuditResult"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[AuthenticationResult] */
        ResponseEnvelope_AuthenticationResult_: {
            data: components["schemas"]["AuthenticationResult"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[DashboardSummary] */
        ResponseEnvelope_DashboardSummary_: {
            data: components["schemas"]["DashboardSummary"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[DeviationValidationResult] */
        ResponseEnvelope_DeviationValidationResult_: {
            data: components["schemas"]["DeviationValidationResult"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[DeviceCodePrompt] */
        ResponseEnvelope_DeviceCodePrompt_: {
            data: components["schemas"]["DeviceCodePrompt"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[DiagnosticsResult] */
        ResponseEnvelope_DiagnosticsResult_: {
            data: components["schemas"]["DiagnosticsResult"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[Finding] */
        ResponseEnvelope_Finding_: {
            data: components["schemas"]["Finding"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[GraphCollectionResult] */
        ResponseEnvelope_GraphCollectionResult_: {
            data: components["schemas"]["GraphCollectionResult"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[HealthResponse] */
        ResponseEnvelope_HealthResponse_: {
            data: components["schemas"]["HealthResponse"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[KnowledgePackManifest] */
        ResponseEnvelope_KnowledgePackManifest_: {
            data: components["schemas"]["KnowledgePackManifest"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[KnowledgePackSummary] */
        ResponseEnvelope_KnowledgePackSummary_: {
            data: components["schemas"]["KnowledgePackSummary"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[LocalPreferences] */
        ResponseEnvelope_LocalPreferences_: {
            data: components["schemas"]["LocalPreferences"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[PackValidationReport] */
        ResponseEnvelope_PackValidationReport_: {
            data: components["schemas"]["PackValidationReport"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[PaginatedResponse[ConflictResult]] */
        ResponseEnvelope_PaginatedResponse_ConflictResult__: {
            data: components["schemas"]["PaginatedResponse_ConflictResult_"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[PaginatedResponse[Finding]] */
        ResponseEnvelope_PaginatedResponse_Finding__: {
            data: components["schemas"]["PaginatedResponse_Finding_"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[PaginatedResponse[PolicyEvaluation]] */
        ResponseEnvelope_PaginatedResponse_PolicyEvaluation__: {
            data: components["schemas"]["PaginatedResponse_PolicyEvaluation_"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[PolicyEvaluation] */
        ResponseEnvelope_PolicyEvaluation_: {
            data: components["schemas"]["PolicyEvaluation"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[PublicSettings] */
        ResponseEnvelope_PublicSettings_: {
            data: components["schemas"]["PublicSettings"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[SignOutResult] */
        ResponseEnvelope_SignOutResult_: {
            data: components["schemas"]["SignOutResult"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[TenantStatus] */
        ResponseEnvelope_TenantStatus_: {
            data: components["schemas"]["TenantStatus"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[TokenCacheClearResult] */
        ResponseEnvelope_TokenCacheClearResult_: {
            data: components["schemas"]["TokenCacheClearResult"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[VersionResponse] */
        ResponseEnvelope_VersionResponse_: {
            data: components["schemas"]["VersionResponse"];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[dict[str, bool]] */
        ResponseEnvelope_dict_str__bool__: {
            /** Data */
            data: {
                [key: string]: boolean;
            };
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[dict[str, int]] */
        ResponseEnvelope_dict_str__int__: {
            /** Data */
            data: {
                [key: string]: number;
            };
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[dict[str, list[str]]] */
        ResponseEnvelope_dict_str__list_str___: {
            /** Data */
            data: {
                [key: string]: string[];
            };
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[list[KnowledgePackSummary]] */
        ResponseEnvelope_list_KnowledgePackSummary__: {
            /** Data */
            data: components["schemas"]["KnowledgePackSummary"][];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[list[dict[str, object]]] */
        ResponseEnvelope_list_dict_str__object___: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** ResponseMeta */
        ResponseMeta: {
            /** Request Id */
            request_id: string;
        };
        /** RuntimeEvidence */
        RuntimeEvidence: {
            state: components["schemas"]["RuntimeState"];
            /** Targeted Count */
            targeted_count?: number | null;
            /** Success Count */
            success_count?: number | null;
            /** Error Count */
            error_count?: number | null;
            /** Conflict Count */
            conflict_count?: number | null;
            /** Pending Count */
            pending_count?: number | null;
            /** Not Applicable Count */
            not_applicable_count?: number | null;
            /** Report Timestamp */
            report_timestamp?: string | null;
            source?: components["schemas"]["EvidenceSource"] | null;
            /** Api Version */
            api_version?: string | null;
        };
        /**
         * RuntimeState
         * @enum {string}
         */
        RuntimeState: "succeeded" | "error" | "conflict" | "pending" | "not_applicable" | "unknown";
        /**
         * Scope
         * @enum {string}
         */
        Scope: "device" | "user" | "both" | "unknown";
        /** SettingEvaluation */
        SettingEvaluation: {
            observation: components["schemas"]["SettingObservation"];
            raw_alignment_status: components["schemas"]["AlignmentStatus"];
            effective_alignment_status: components["schemas"]["AlignmentStatus"];
            microsoft_value?: components["schemas"]["JsonValue"];
            /** Baseline Product */
            baseline_product?: string | null;
            /** Baseline Version */
            baseline_version?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceSource"][];
            evidence_confidence: components["schemas"]["EvidenceConfidence"];
            applicability: components["schemas"]["ApplicabilityState"];
            /** Applicability Reasons */
            applicability_reasons?: string[];
            /** Not Evaluable Reasons */
            not_evaluable_reasons?: string[];
            /** Trace */
            trace?: components["schemas"]["DecisionTraceStep"][];
        };
        /** SettingObservation */
        SettingObservation: {
            /** Observation Id */
            observation_id: string;
            /** Original Setting Id */
            original_setting_id: string;
            /** Normalized Setting Id */
            normalized_setting_id: string;
            /** Canonical Setting Id */
            canonical_setting_id: string;
            /** Definition Id */
            definition_id?: string | null;
            /** Choice Id */
            choice_id?: string | null;
            /** Value Definition Id */
            value_definition_id?: string | null;
            original_value?: components["schemas"]["JsonValue"];
            canonical_value?: components["schemas"]["JsonValue"];
            /** Display Value */
            display_value: string;
            /** Technical Json Path */
            technical_json_path: string;
            /** Source Policy Id */
            source_policy_id: string;
            /** Source Policy Name */
            source_policy_name: string;
            /** Source File */
            source_file: string;
            platform: components["schemas"]["Platform"];
            scope: components["schemas"]["Scope"];
            extraction_confidence: components["schemas"]["EvidenceConfidence"];
            /** Parser Name */
            parser_name: string;
            /** Parser Version */
            parser_version: string;
            /** Diagnostics */
            diagnostics?: components["schemas"]["ParserDiagnostic"][];
        };
        /** SignOutResult */
        SignOutResult: {
            /** Signed Out */
            signed_out: boolean;
            /** Token Cache Deleted */
            token_cache_deleted: boolean;
        };
        /** TenantStatus */
        TenantStatus: {
            /** Configured */
            configured: boolean;
            /** Authenticated */
            authenticated: boolean;
            /** Requested Scopes */
            requested_scopes: string[];
            /** Granted Scopes */
            granted_scopes: string[];
            /** Account Name */
            account_name?: string | null;
            /** Operations */
            operations: {
                [key: string]: string;
            };
            /** Last Retrieval At */
            last_retrieval_at?: string | null;
            /**
             * Implementation State
             * @default safe_skeleton
             */
            implementation_state: string;
            /** Limitations */
            limitations?: string[];
        };
        /** TokenCacheClearResult */
        TokenCacheClearResult: {
            /** Token Cache Deleted */
            token_cache_deleted: boolean;
        };
        /** UploadedSource */
        UploadedSource: {
            /** Source Id */
            source_id: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
            /** Archive Member */
            archive_member?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Application */
            application: string;
            /** Api */
            api: string;
            /** Audit Schema */
            audit_schema: string;
            /** Knowledge Pack Schema */
            knowledge_pack_schema: string;
            /** Report Schema */
            report_schema: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_HealthResponse_"];
                };
            };
        };
    };
    version_api_v1_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_VersionResponse_"];
                };
            };
        };
    };
    public_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_PublicSettings_"];
                };
            };
        };
    };
    update_settings_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalPreferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_LocalPreferences_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_history_api_v1_settings_audit_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_list_dict_str__object___"];
                };
            };
        };
    };
    delete_local_audit_data_api_v1_settings_local_audit_data_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_dict_str__int__"];
                };
            };
        };
    };
    clear_temporary_files_api_v1_settings_clear_temporary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_dict_str__int__"];
                };
            };
        };
    };
    clear_token_cache_api_v1_settings_clear_token_cache_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_TokenCacheClearResult_"];
                };
            };
        };
    };
    reset_application_settings_api_v1_settings_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_dict_str__int__"];
                };
            };
        };
    };
    diagnostics_api_v1_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_DiagnosticsResult_"];
                };
            };
        };
    };
    validate_deviations_api_v1_deviations_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_validate_deviations_api_v1_deviations_validate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_DeviationValidationResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_demo_audit_api_v1_audits_demo_post: {
        parameters: {
            query?: {
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_AuditResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_offline_audit_api_v1_audits_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_offline_audit_api_v1_audits_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_AuditPreview_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_offline_audit_api_v1_audits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_offline_audit_api_v1_audits_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_AuditResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audit_api_v1_audits__audit_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_AuditResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_v1_audits__audit_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_DashboardSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policies_api_v1_audits__audit_id__policies_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                search?: string | null;
                sort_by?: ("name" | "platform" | "kind") | null;
                sort_order?: "asc" | "desc";
            };
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_PaginatedResponse_PolicyEvaluation__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    policy_detail_api_v1_audits__audit_id__policies__policy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
                policy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_PolicyEvaluation_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findings_api_v1_audits__audit_id__findings_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                severity?: components["schemas"]["FindingSeverity"] | null;
                alignment?: components["schemas"]["AlignmentStatus"] | null;
                search?: string | null;
                sort_by?: ("severity" | "policy" | "alignment" | "type") | null;
                sort_order?: "asc" | "desc";
            };
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_PaginatedResponse_Finding__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finding_detail_api_v1_audits__audit_id__findings__finding_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_Finding_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conflicts_api_v1_audits__audit_id__conflicts_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                confidence?: components["schemas"]["ConflictConfidence"] | null;
                sort_by?: ("confidence" | "classification" | "setting") | null;
                sort_order?: "asc" | "desc";
            };
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_PaginatedResponse_ConflictResult__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_catalog_api_v1_audits__audit_id__reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                audit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_dict_str__list_str___"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_report_api_v1_audits__audit_id__reports__report_format__get: {
        parameters: {
            query?: {
                language?: string;
            };
            header?: never;
            path: {
                audit_id: string;
                report_format: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_packs_api_v1_knowledge_packs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_list_KnowledgePackSummary__"];
                };
            };
        };
    };
    validate_knowledge_pack_api_v1_knowledge_packs_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_validate_knowledge_pack_api_v1_knowledge_packs_validate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_PackValidationReport_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_knowledge_pack_api_v1_knowledge_packs_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_knowledge_pack_api_v1_knowledge_packs_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_KnowledgePackSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_pack_api_v1_knowledge_packs__pack_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_KnowledgePackSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_pack_api_v1_knowledge_packs__pack_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_KnowledgePackSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_pack_api_v1_knowledge_packs__pack_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_dict_str__bool__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pack_provenance_api_v1_knowledge_packs__pack_id__provenance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_KnowledgePackManifest_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_pack_validation_report_api_v1_knowledge_packs__pack_id__validation_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pack_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_tenant_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_TenantStatus_"];
                };
            };
        };
    };
    begin_device_code_api_v1_tenant_device_code_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_DeviceCodePrompt_"];
                };
            };
        };
    };
    begin_device_code_api_v1_tenant_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_DeviceCodePrompt_"];
                };
            };
        };
    };
    complete_device_code_api_v1_tenant_device_code_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteDeviceCode"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_AuthenticationResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_api_v1_tenant_retrieve__operation__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_GraphCollectionResult_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_out_api_v1_tenant_signout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_SignOutResult_"];
                };
            };
        };
    };
}
